#### Тема “Вычисления с помощью Numpy”

### task_1

In [1]:
import numpy as np

In [78]:
a = np.array([[1, 2, 3, 3, 1],[6, 8, 11, 10, 7]]).T

In [4]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [10]:
mean_a = a.mean(axis = 0 )

In [18]:
mean_a

array([2. , 8.4])

### task_2

In [19]:
a_centered = a - mean_a 

In [20]:
a_centered

array([[-1. , 41.6],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### task_3

In [74]:
a_centered_sp = np.dot(a_centered[:,0], a_centered[:,1])
a_centered_sp / (len(a_centered)- 1)

-9.0

### task_4

In [77]:
np.cov(a.T)[0, 1]

-9.0